### ISSUE TITLE
Lexique français/anglais

### ISSUE THREAD

**Issue by olange** [DiscoverMeteor/DiscoverMeteor_fr#10]
Voici quelques suggestions pour le lexique anglais/français. Je suggèrerais de créer une page dans le Wiki pour ce lexique des traducteurs.

Les [Translation Guidelines](https://www.discovermeteor.com/guidelines) suggèrent de les placer dans un fichier `COMMON.md` – aux dépens de la publication statique avec MiddleMan, qui permet de prévisualiser les traductions réalisées, mais qui ne fonctionne plus lorsqu'on place un tel fichier à la racine `source/chapters/fr` (où le repo _DiscoverMeteor_fr_ est monté).

Voici déjà mes propositions:

* **Packages**: _paquets_ (les distros Linux telles que Debian/Ubuntu l'ont popularisé en français); **smart package**: _paquet intelligent_; **core package**: _paquet essentiel_
* **Core**: _coeur_, ou _noyau_
* A **build**: un _assemblage_
* **Assets**: _ressources_; **static assets**: _ressources statiques_
* **Pattern**: _pattern_; la traduction «motifs de conception» est peu claire
* **Framework**: _framework_; tellement usité, difficile de faire mieux
* **File structure**: _structure de fichiers_

J'ai utilisé ces locutions dans ma traduction du chapitre 2.

**Comment by Keho** [comment]
Il faudra intégrer ça dans le wiki
