### ISSUE TITLE
Chapitre 5: spin package

### ISSUE THREAD

**Issue by adelivet** [DiscoverMeteor/DiscoverMeteor_fr#117]
Dans le chapitre 5, la commande `mrt add spin` n'est pas bonne, c'est `add sacha:spin`.

**Comment by Keho** [comment]
Bonjour @adelivet, et merci de votre retour.

Je n'ai pas trouvé la commande `mrt add spin` dans le fichier 05.
Peut-être l'avez vous vue sur [Découvrir Meteor](http://fr.discovermeteor.com/ ) : le site est généré grâce au dépôt [DiscoverMeteorStatic](https://github.com/DiscoverMeteor/DiscoverMeteorStatic), qui n'est pas actuellement synchronisé avec ce dépôt (je ne sais pas comment le faire).
Du coup la version affiché sur le site utilise encore mrt.
