### ISSUE TITLE
Traduction de "sidebar"

### ISSUE THREAD

**Issue by OyoKooN** [DiscoverMeteor/DiscoverMeteor_fr#2]
Bonjour,

Je vois que @newnectar a utilisé "marge" pour traduire "sidebar" mais je me demande si on ne peut pas trouver une meilleure traduction qui refléterait plus le statut de ces chapitres.

Des idées ?

**Comment by Keho** [comment]
Pour l'instant aparté semble l'avoir emporté, mais je préfère encart.
Qu'en pensez-vous ?
