### ISSUE TITLE
Chapitre 9 en cours de màj.

### ISSUE THREAD

**Issue by Miand** [DiscoverMeteor/DiscoverMeteor_fr#45]
Le chapitre 09 est traduit. Vous pouvez proposer des améliorations.

**Comment by arnaudvalle** [comment]
@Imote Pour info, je suis en train de relire / mettre à jour ce chapitre

**Comment by Keho** [comment]
Bonjour @arnaudvalle pouvez vous confirmer que vous êtes toujours en train de mettre à jour ce chapitre ?

**Comment by arnaudvalle** [comment]
@Keho j'ai relu / mis à jour les 3/4 du chapitre (mais je n'ai pas fais grand chose depuis un bon mois) jusque <%= commit "9-3", "Effacer les erreurs après 3 secondes." %>
Je peux créer une PR qui pourra être complétée si besoin?

**Comment by Keho** [comment]
C'est une bonne idée ! Merci ;)

**Comment by arnaudvalle** [comment]
@Keho j'ai mis à jour le chapitre 9 avec ce que j'avais fait jusque là. Pour info j'avais relu / traduit jusqu'à la ligne 252 (<%= commit "9-3", "Effacer les erreurs après 3 secondes." %>) mais je n'ai pas trop suivi si il y avait eu de nouvelles mise à jour ces deux derniers mois.
