### ISSUE TITLE
Bye Bye Meteorite! - mettre à jour traduction du chapitre 02

### ISSUE THREAD

**Issue by remremo** [DiscoverMeteor/DiscoverMeteor_fr#59]
Salut je viens de lire un extrait de la version anglaise et espagnole disant que meteorite n est plus necessaire, est ce normal que l on demande de l installer dans la version francaise.

English
Bye Bye Meteorite
There was a time where Meteor relied on an external package manager called Meteorite. Since Meteor version 0.9.0, Meteorite is not needed anymore since its features have been assimilated into Meteor itself.
So if you encounter any references to Meteorite's mrt command line utility throughout this book or while browsing Meteor-related material, you can safely replace them by the usual meteor.

French
Meteorite
Meteor n'ayant pas encore de support pour des paquets (packages) tiers, Tom Coleman (l'un des auteurs de ce livre), et des membres de la communauté, ont créé Meteorite, une surcouche de Meteor. Meteorite enrichit Meteor de commandes qui permettent d'installer Meteor, et de lui ajouter les paquets que vous souhaiteriez.
Comme nous allons utiliser des paquets tiers pour une part des fonctionnalités de Microscope, installons Meteorite.

Spanish Version
Bye Bye Meteorite
Hubo un tiempo en el que Meteor utilizaba un gestor de paquetes externo llamado Meteorite. Desde la versión 0.9.0 de Meteor, Meteorite ya no es necesario, ya que sus características se han incorporado a Meteor.
Así que si encuentras referencias a mrt de de Meteorite a lo largo de este libro o mientras lees material relacionado con Meteor, puedes reemplazarlo con total seguridad por el habitual meteor.

Voila peut etre que ca vous aidera, je peux traduire aussi si vous avez besoin.

Ciao et bonne continuation

**Comment by arnaudvalle** [comment]
chapitre mis à jour
