### ISSUE TITLE
Quelqu'un s'occupe du chapitre 8?

### ISSUE THREAD

**Issue by Imote** [DiscoverMeteor/DiscoverMeteor_fr#72]
Bonjour :)
J'aimerai savoir si quelqu'un est actuellement en train de traduire le chapitre 8 ou pas ? https://github.com/DiscoverMeteor/DiscoverMeteor_fr/blob/master/08-editing-posts.md.erb
Si ce n'est pas le cas je me ferai un plaisir de le traduire en entier maintenant que j'ai accès au livre original :)

**Comment by arnaudvalle** [comment]
Tu peux y aller, je ne pense pas que quelqu'un ai commencé - si tu pouvais mettre le tout dans une PR ça serait parfait (c'est bcp plus simple à relire et corriger je trouve).

**Comment by Imote** [comment]
oui oui je comptais envoyer ça en PR pour avoir une validation bien sur avant et pour peaufiner :)

**Comment by Imote** [comment]
Voilà, effectuer sur la PR #73
