### ISSUE TITLE
Comment nommer les helpers ?

### ISSUE THREAD

**Issue by Imote** [DiscoverMeteor/DiscoverMeteor_fr#75]
Dans la traduction de ce livre, notamment dans ce fichier :
https://github.com/DiscoverMeteor/DiscoverMeteor_fr/blob/master/03-templates.md.erb
les helpers sont nommé managers en français. Ne serait t'il pas préférable de garder le terme helper qui est universel même dans le code par soucis de compréhension ? Car moi même quand j'ai lu le livre je l'ai lu très très vite je n'avais pas saisi ce qu'était un manager mais j'avais saisis ce qu'étais un helper (j'avais pas pigé que c'était la même chose xD).

**Comment by arnaudvalle** [comment]
Les helpers et les managers sont deux choses différentes il me semble donc il est important de les différencier. Si tu relis la version originale (https://github.com/DiscoverMeteor/DiscoverMeteor_En/blob/master/03-templates.md.erb) tu devrais voir la différence.

**Comment by Imote** [comment]
Car, *si je me trompe pas*, le texte expliquant les helpers en français utilise le terme manager (à vérifier). Je regarde après et corrige au besoin ;)

**Comment by arnaudvalle** [comment]
ah ok c'est peut-être juste qu'ils ont été inversé par erreur dans ce cas là
