### ISSUE TITLE
relecture typos & erreurs

### ISSUE THREAD

**Issue by Keho** [DiscoverMeteor/DiscoverMeteor_fr#78]
Bonjour,

J'ai relevé quelques erreurs de français dans le chapitre 4.5. Je voudrais bien les corriger directement mais je suppose qu'il faut être dans le groupe :

- quand Meteor n'étaient => n'était
- une simple applications => application
- le client envoit => envoie
- Bob, etc... => Bob, etc. ou Bob... tout court
- un joli, HTML => un joli HTML
- Finalement, l'application prends => prend
- qui va s'executer => s'exécuter
* qui ne trouve pas seulement le livre pour vous, mais qui vous suit jusque chez vous pour vous lire le livre => qui non seulement vous trouve le livre, mais aussi vous suit jusque chez vous pour vous le lire
- (ce que => qui
-  un sous-ensemble de votre base de données et la => le
- la donnée brute, actuelle et => brute, actuelle, et
- lesquels peuvent être privé ou sensible => privés ou sensibles
* Donc nous n'allons évidemment pas juste copier notre entière base de données => Donc nous n'allons évidemment pas entièrement copier notre base de données
- ils ne devront pas être rendu disponible => rendus disponibles
- (i.e. envoyé => envoyés
- collection coté-serveur => côté serveur (le tiret n'est pas nécessaire)
- collection coté-client  => côté client
* (one of the founders of Meteor) => on peut traduire ça, non ? un des fondateurs de Meteor
* screencast => capture vidéo
* le moindre détail => les moindres détails (mais c'est un détail :P)
* nous ne pouvons pas juste envoyer => nous ne pouvons pas (simplement) envoyer (juste est très souvent mal employé par anglicisme) 
- les données auquelles vous souscrivez sera dupliqué sur le client grace à => auxquelles, seront dupliquées, grâce
- MongoDB coté-client => côté client
- Premièrement, nous modifierions [...] Et nous définirons => 
soit le conditionnel pour les deux : nous modifierions [...] Et nous définirions
soit le futur pour les deux : nous modifierons [...] Et nous définirons
- dans le code coté-client => côté client
- application Meteor adaptable coté-client => je ne vais pas lâcher l'affaire :D
- on choisit les parties que nous avons actuellement besoin => dont nous avons
- les surcharge mémoire => les surcharges mémoire
- base de données coté-serveur => côté serveur
- arrivent à être étiqueté => étiquetés
* Maintenant que les articles de Bob arrivent à être étiqueté dans plusieurs catégories (par exemple : “Javascript”, “Ruby, et "Python”). Peut-être que nous voulons toujours charger tous les articles de Bob en mémoire, mais nous voulons seulement afficher ceux de la catégorie “Javascript”. C'est ici que “trouver” intervient. => *_* à revoir entièrement !
Maintenant qu'il est possible d'étiqueter les articles de Bob dans plusieurs catégories (par exemple "Javascript", "Ruby" et "Python"), on pourrait avoir envie de continuer de charger tous les articles en mémoire mais de n'afficher que ceux de la catégorie "Javascript". C'est dans ce cas de figure que "trouver" intervient.
(à noter qu'à ce moment du cours on n'a pas expliqué comment étiqueter des articles...)
* Juste comme nous l'avons fait => Comme nous l'avons fait
- quel rôle joue les publications => jouent
* Comme point de départ, discutons de ce que ça fait exactement. => Commençons par discuter de son rôle.
- vous avez une collection appelées => appelée
- vers une collections appelées => collection appelée
* et que vous n'avez pas encore réfléchi sur les publications => réfléchi aux publications
* vous allez rapidement réaliser => vous allez rapidement vous rendre compte (anglicisme)

je me suis arrêté ici parce que le chapitre est bizarrement organisé et est redondant avec la fin du chapitre 4.

En tout cas merci à l'équipe pour le travail de traduction :)

**Comment by Imote** [comment]
De trop nombreux chapitres sont carrément hors contexte, le livre a beaucoup évolué depuis la traduction, il faut revoir presque en entier le livre français :p

**Comment by Imote** [comment]
Mais merci de ton retour ;)
Je me repencherai sur la traduction très vite étant donné que je suis enfin en vacances !!

**Comment by Keho** [comment]
Je suis partant pour aider à traduire :)
La version anglaise à jour est disponible gratuitement ?

**Comment by Imote** [comment]
non il faut la payer mais si tu fais partie de la team tu peux avoir un accès au livre anglais pour le traduire :) tu dois mentioner https://github.com/SachaG dans une issue demandant d'être dans la team pour traduire :)
